### ISSUE TITLE
recent commit

### ISSUE THREAD

**Issue by Atomu2014** [Dunni3/FlowMol#9]
Hi,

I just pulled your new commits and found you did quite a lot of changes recently, including many dependency changes. I wonder when you can release a stable version? And will the dependencies change any more?

Thanks

**Comment by Dunni3** [comment]
Hi there, 

This repository contains research code and as such it is unfortunately subject to change. The latest PR contains an implementation of CTMC-based flows for categorical data that substantially improves the performance of the model, and this update is accompanied by a second paper. 

However, we will make available tags/releases for major updates. I've created a v0.1 tag for a commit corresponding with our first preprint and will add a second tag shortly for the second preprint we just posted. 

That being said, all of the trained models and the types of models from the first version of FlowMol should still work under the current version. 

Feel free to reach out or raise another issue if you have questions/problems. 

Best,
Ian

**Comment by Atomu2014** [comment]
Thanks. I will update to v0.1.
